# Generated by Django 5.1.2 on 2024-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dis', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('count', models.CharField(max_length=30)),
                ('storage', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=10)),
            ],
        ),
    ]
